ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "countryCode" varchar(2) NOT NULL DEFAULT 'NG';
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "currencyCode" varchar(3) NOT NULL DEFAULT 'NGN';
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "sourceUrl" text;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "sourceType" varchar(60) NOT NULL DEFAULT 'owner_submission';
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "sellingConditions" text;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "buyerCosts" text;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "availabilityDate" timestamp;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "contactPermission" integer NOT NULL DEFAULT 0;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "reviewState" varchar(40) NOT NULL DEFAULT 'approved';
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "submittedBy" integer;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "approvedBy" integer;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "approvedAt" timestamp;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "lastReviewedAt" timestamp;
ALTER TABLE "internationalProspects" ADD COLUMN IF NOT EXISTS "category" varchar(120) NOT NULL DEFAULT 'real_estate_partner';
ALTER TABLE "internationalProspects" ADD COLUMN IF NOT EXISTS "website" text;
ALTER TABLE "internationalProspects" ADD COLUMN IF NOT EXISTS "sourceType" varchar(80) NOT NULL DEFAULT 'public_directory';
ALTER TABLE "internationalProspects" ADD COLUMN IF NOT EXISTS "sourceUrl" text;
ALTER TABLE "internationalProspects" ADD COLUMN IF NOT EXISTS "collectedAt" timestamp NOT NULL DEFAULT now();
ALTER TABLE "internationalProspects" ADD COLUMN IF NOT EXISTS "confidence" varchar(40) NOT NULL DEFAULT 'needs_review';
ALTER TABLE "internationalProspects" ADD COLUMN IF NOT EXISTS "ownerId" integer;
ALTER TABLE "internationalProspects" ADD COLUMN IF NOT EXISTS "nextStep" text;
ALTER TABLE "internationalProspects" ADD COLUMN IF NOT EXISTS "nextStepAt" timestamp;
ALTER TABLE "internationalProspects" ADD COLUMN IF NOT EXISTS "doNotContact" integer NOT NULL DEFAULT 0;
ALTER TABLE "internationalProspectContacts" ADD COLUMN IF NOT EXISTS "sourceType" varchar(80) NOT NULL DEFAULT 'public_business_source';
ALTER TABLE "internationalProspectContacts" ADD COLUMN IF NOT EXISTS "confidence" varchar(40) NOT NULL DEFAULT 'needs_review';
ALTER TABLE "internationalProspectContacts" ADD COLUMN IF NOT EXISTS "doNotContact" integer NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS "properties_country_idx" ON "properties" ("countryCode");
CREATE INDEX IF NOT EXISTS "properties_review_idx" ON "properties" ("reviewState");
CREATE INDEX IF NOT EXISTS "prospects_country_idx" ON "internationalProspects" ("countryCode");
